extends Node

const BASE_ENEMIES = {
	"dummy":{
		"base_name":["dummy"],
		"lesser_prefix":["broken","straw","one-armed","headless"],
		"greater_prefix":["training","reinforced","steel-clad","crash test"],
		"abilities":[],
		"exp":0,
		"base_stats":{
			"strength":4,
			"constitution":40,
			"dexterity":4,
			"intelligence":4,
			"wisdom":4,
			"cunning":4,
		},
		"attributes":{
			"attack":5,
			"magic":5,
			"willpower":20,
			"armour":0,
			"evasion":10,
			"accuracy":10,
			"penetration":0,
			"speed":-5,
			"critical":0,
		},
	},
	"elemental":{
		"base_name":["slime","elemental"],
		"lesser_prefix":["lesser","tiny","small"],
		"greater_prefix":["greater","great","large"],
		"base_stats":{
			"strength":4,
			"constitution":4,
			"dexterity":4,
			"intelligence":8,
			"wisdom":8,
			"cunning":6,
		},
		"attributes":{
			"attack":5,
			"magic":10,
			"willpower":4,
			"armour":0,
			"evasion":0,
			"accuracy":5,
			"penetration":0,
			"speed":2,
			"critical":0,
		},
		"variants":{
			"fire":{
				"name_prefix":["fire","fiery","blaze","flare"],
				"abilities":["feral_fire_magic","feral_impact_fire_magic"],
				"resistance":{
					"fire":0.75,
				},
			},
			"water":{
				"name_prefix":["water","aqua","hydro","ocean"],
				"abilities":["feral_water_magic","feral_impact_water_magic"],
				"resistance":{
					"water":0.75,
				},
			},
			"ice":{
				"name_prefix":["ice","cold","frozen","cryo","frost"],
				"abilities":["feral_ice_magic","feral_impact_ice_magic"],
				"resistance":{
					"ice":0.75,
				},
			},
			"lightning":{
				"name_prefix":["lightning","electro","thunder"],
				"abilities":["feral_lightning_magic","feral_impact_lightning_magic"],
				"resistance":{
					"lightning":0.75,
				},
			},
			"toxic":{
				"name_prefix":["toxic","poison","swamp"],
				"abilities":["feral_poison_magic","feral_impact_poison_magic"],
				"resistance":{
					"poison":0.75,
				},
			},
			"corrosive":{
				"name_prefix":["corrosive","acid"],
				"abilities":["feral_acid_magic","feral_impact_acid_magic"],
				"resistance":{
					"acid":0.75,
				},
			},
		},
		"materials":[
			"slime","condensate","residue","magic_salt"
		],
	},
	"water_elemental":{
		"base_name":["elemental","anomaly"],
		"lesser_prefix":["lesser","weak","small"],
		"greater_prefix":["greater","energized","large"],
		"base_stats":{
			"strength":6,
			"constitution":6,
			"dexterity":6,
			"intelligence":10,
			"wisdom":10,
			"cunning":8,
		},
		"attributes":{
			"attack":15,
			"magic":15,
			"willpower":8,
			"armour":0,
			"evasion":5,
			"accuracy":10,
			"penetration":5,
			"speed":0,
			"critical":0,
		},
		"abilities":["feral_water_magic"],
		"variants":{
			"water":{
				"name_prefix":["water","aqua","hydro","ocean"],
				"abilities":["feral_cutting_water_magic"],
				"resistance":{
					"water":0.75,
					"fire":-0.25,
				},
			},
			"vitalizing":{
				"name_prefix":["life","vitalizing"],
				"abilities":["healing"],
				"resistance":{
					"water":0.75,
					"fire":-0.25,
				},
			},
			"lightning":{
				"name_prefix":["storm","thunder","sparkling"],
				"abilities":["feral_cutting_lightning_magic"],
				"resistance":{
					"water":0.5,
					"lightning":0.5,
				},
			},
			"ice":{
				"name_prefix":["hailstorm","frost","ice"],
				"abilities":["feral_cutting_ice_magic"],
				"resistance":{
					"water":0.5,
					"ice":0.5,
				},
			},
		},
		"exp":15,
		"materials":[
			"condensate","residue","resin","magic_salt",
		],
	},
	"lava_elemental":{
		"base_name":["elemental","anomaly"],
		"lesser_prefix":["lesser","weak","small"],
		"greater_prefix":["greater","energized","large"],
		"base_stats":{
			"strength":6,
			"constitution":6,
			"dexterity":6,
			"intelligence":10,
			"wisdom":10,
			"cunning":8,
		},
		"attributes":{
			"attack":15,
			"magic":15,
			"willpower":8,
			"armour":0,
			"evasion":5,
			"accuracy":10,
			"penetration":5,
			"speed":0,
			"critical":0,
		},
		"abilities":["feral_fire_magic"],
		"variants":{
			"fire":{
				"name_prefix":["lava","magma","fire"],
				"abilities":["feral_cutting_fire_magic"],
				"resistance":{
					"fire":0.75,
					"water":-0.25,
				},
			},
			"vitalizing":{
				"name_prefix":["molten lava","liquid fire","mending magma"],
				"abilities":["healing"],
				"resistance":{
					"fire":0.75,
					"water":-0.25,
				},
			},
			"darkness":{
				"name_prefix":["fearfire","heallfire","shadow flame","blue fire"],
				"abilities":["feral_cutting_darkness_magic"],
				"resistance":{
					"fire":0.5,
					"darkness":0.5,
				},
			},
			"earth":{
				"name_prefix":["basalt","ash","solid lava"],
				"abilities":["feral_cutting_earth_magic"],
				"resistance":{
					"fire":0.5,
					"impact":0.25,
					"cutting":0.25,
					"piercing":0.25,
				},
			},
		},
		"exp":15,
		"materials":[
			"condensate","residue","resin","magic_salt",
		],
	},
	"shadow_elemental":{
		"base_name":["elemental","anomaly"],
		"lesser_prefix":["lesser","weak","small"],
		"greater_prefix":["greater","energized","large"],
		"base_stats":{
			"strength":6,
			"constitution":6,
			"dexterity":6,
			"intelligence":10,
			"wisdom":10,
			"cunning":8,
		},
		"attributes":{
			"attack":15,
			"magic":15,
			"willpower":8,
			"armour":0,
			"evasion":5,
			"accuracy":10,
			"penetration":5,
			"speed":0,
			"critical":0,
		},
		"abilities":["feral_darkness_magic"],
		"variants":{
			"shadow":{
				"name_prefix":["shadow","darkness","pitch black"],
				"abilities":["feral_cutting_darkness_magic"],
				"resistance":{
					"darkness":0.75,
					"light":-0.25,
				},
			},
			"shielding":{
				"name_prefix":["dark barrier","shadow field","darkness infused"],
				"abilities":["defensive_magic"],
				"resistance":{
					"darkness":0.75,
					"light":-0.25,
				},
			},
			"lightning":{
				"name_prefix":["storm","thunder","sparkling"],
				"abilities":["feral_cutting_lightning_magic"],
				"resistance":{
					"darkness":0.5,
					"lightning":0.5,
				},
			},
			"fire":{
				"name_prefix":["fear fire","hell fire","shadow flame"],
				"abilities":["feral_cutting_fire_magic"],
				"resistance":{
					"darkness":0.5,
					"fire":0.5,
				},
			},
		},
		"exp":15,
		"materials":[
			"condensate","residue","resin","magic_salt",
		],
	},
	"cloud_elemental":{
		"base_name":["elemental","anomaly"],
		"lesser_prefix":["lesser","weak","small"],
		"greater_prefix":["greater","energized","large"],
		"base_stats":{
			"strength":6,
			"constitution":6,
			"dexterity":6,
			"intelligence":10,
			"wisdom":10,
			"cunning":8,
		},
		"attributes":{
			"attack":15,
			"magic":15,
			"willpower":8,
			"armour":0,
			"evasion":8,
			"accuracy":8,
			"penetration":4,
			"speed":0,
			"critical":0,
		},
		"abilities":["feral_wind_magic","feral_water_magic"],
		"variants":{
			"cloud":{
				"name_prefix":["cloud","foggy"],
				"abilities":["feral_cutting_wind_magic","feral_cutting_water_magic"],
				"resistance":{
					"wind":0.5,
					"water":0.5,
				},
			},
			"evading":{
				"name_prefix":["slippery","thin","evasive"],
				"abilities":["evasion"],
				"resistance":{
					"wind":0.5,
					"water":0.5,
				},
			},
			"lightning":{
				"name_prefix":["storm","thunder","sparkling"],
				"abilities":["feral_cutting_lightning_magic"],
				"resistance":{
					"wind":0.5,
					"lightning":0.5,
				},
			},
			"steam":{
				"name_prefix":["steam","scalding"],
				"abilities":["feral_cutting_fire_magic"],
				"resistance":{
					"water":0.5,
					"fire":0.5,
				},
			},
		},
		"exp":15,
		"materials":[
			"condensate","residue","resin","magic_salt",
		],
	},
	"nanite_swarm":{
		"base_name":["nanite swarm"],
		"lesser_prefix":["lesser","weak","thin"],
		"greater_prefix":["greater","energized","dense"],
		"base_stats":{
			"strength":6,
			"constitution":7,
			"dexterity":10,
			"intelligence":12,
			"wisdom":12,
			"cunning":10,
		},
		"attributes":{
			"attack":10,
			"magic":20,
			"willpower":15,
			"armour":-5,
			"evasion":20,
			"accuracy":10,
			"penetration":8,
			"speed":0,
			"critical":0,
		},
		"resistance":{
			"poison":0.75,
			"acid":-0.25,
		},
		"abilities":["elemental_magic","evasion"],
		"variants":{
			"charged":{
				"name_prefix":["charged","sparkling","energized"],
				"abilities":["feral_cutting_lightning_magic","high_tech_ranged","defensive_magic"],
				"resistance":{
					"wind":0.5,
					"lightning":0.5,
				},
			},
			"metallic":{
				"name_prefix":["metallic","solid"],
				"abilities":["high_tech_cutting","dirty_fighting"],
				"resistance":{
					"impact":0.4,
					"light":0.5,
					"darkness":0.5,
				},
			},
		},
		"exp":15,
		"materials":[
			"condensate","residue","resin","magic_salt",
		],
	},
	"nanite_slime":{
		"base_name":["slime","anomaly"],
		"lesser_prefix":["lesser","weak","small"],
		"greater_prefix":["greater","energized","large"],
		"base_stats":{
			"strength":6,
			"constitution":6,
			"dexterity":6,
			"intelligence":10,
			"wisdom":10,
			"cunning":8,
		},
		"attributes":{
			"attack":15,
			"magic":15,
			"willpower":8,
			"armour":4,
			"evasion":5,
			"accuracy":10,
			"penetration":5,
			"speed":0,
			"critical":0,
		},
		"abilities":["feral_lightning_magic"],
		"variants":{
			"lightning":{
				"name_prefix":["supercharged","overcharged","sparkling"],
				"abilities":["feral_impact_lightning_magic"],
				"resistance":{
					"lightning":0.75,
				},
			},
			"nanite":{
				"name_prefix":["nanite","nanobot"],
				"abilities":["healing","dirty_fighting"],
				"resistance":{
					"piercing":0.25,
					"cutting":0.25,
					"impact":0.25,
				},
			},
		},
		"exp":15,
		"materials":[
			"condensate","resin","tissue","scrap",
		],
	},
	"mud_slime":{
		"base_name":["slime","anomaly"],
		"lesser_prefix":["lesser","weak","small"],
		"greater_prefix":["greater","infused","large"],
		"base_stats":{
			"strength":6,
			"constitution":6,
			"dexterity":6,
			"intelligence":10,
			"wisdom":10,
			"cunning":8,
		},
		"attributes":{
			"attack":15,
			"magic":15,
			"willpower":8,
			"armour":4,
			"evasion":5,
			"accuracy":10,
			"penetration":5,
			"speed":0,
			"critical":0,
		},
		"abilities":["feral_water_magic"],
		"variants":{
			"water":{
				"name_prefix":["water","aqua","hydro","ocean"],
				"abilities":["feral_cutting_water_magic"],
				"resistance":{
					"water":0.75,
					"fire":-0.25,
				},
			},
			"vitalizing":{
				"name_prefix":["life","vitalizing"],
				"abilities":["healing"],
				"resistance":{
					"water":0.75,
					"fire":-0.25,
				},
			},
			"earth":{
				"name_prefix":["earth","geo","sand","rock"],
				"abilities":["feral_impact_earth_magic"],
				"resistance":{
					"impact":0.25,
					"cutting":0.25,
					"piercing":0.25,
				},
			},
			"air":{
				"name_prefix":["air","wind"],
				"abilities":["feral_cutting_wind_magic"],
				"resistance":{
					"impact":0.1,
					"cutting":0.1,
					"piercing":0.1,
					"air":0.5,
				},
			},
		},
		"exp":15,
		"materials":[
			"condensate","residue","resin","magic_salt",
		],
	},
	"spirit":{
		"base_name":["spirit","ghost"],
		"lesser_prefix":["lesser","weak","dim"],
		"greater_prefix":["greater","empowered","radiant"],
		"base_stats":{
			"strength":4,
			"constitution":6,
			"dexterity":8,
			"intelligence":8,
			"wisdom":8,
			"cunning":8,
		},
		"attributes":{
			"attack":0,
			"magic":15,
			"willpower":12,
			"armour":0,
			"evasion":10,
			"accuracy":5,
			"penetration":10,
			"speed":0,
			"critical":2,
		},
		"resistance":{
			"impact":0.5,
			"cutting":0.5,
			"piercing":0.5,
		},
		"variants":{
			"fire":{
				"name_prefix":["fire","fiery","blaze","flare"],
				"abilities":["feral_fire_magic","feral_impact_fire_magic"],
				"resistance":{
					"fire":0.75,
				},
			},
			"water":{
				"name_prefix":["water","aqua","hydro","ocean"],
				"abilities":["feral_water_magic","feral_impact_water_magic"],
				"resistance":{
					"water":0.75,
				},
			},
			"ice":{
				"name_prefix":["ice","cold","frozen","cryo","frost"],
				"abilities":["feral_ice_magic","feral_impact_ice_magic"],
				"resistance":{
					"ice":0.75,
				},
			},
			"lightning":{
				"name_prefix":["lightning","electro","thunder"],
				"abilities":["feral_lightning_magic","feral_impact_lightning_magic"],
				"resistance":{
					"lightning":0.75,
				},
			},
			"light":{
				"name_prefix":["light","shining","radiant"],
				"abilities":["feral_light_magic","feral_impact_light_magic"],
				"resistance":{
					"light":0.75,
				},
			},
			"darkness":{
				"name_prefix":["dark","shadow","black"],
				"abilities":["feral_darkness_magic","feral_impact_darkness_magic"],
				"resistance":{
					"darkness":0.75,
				},
			},
		},
		"materials":[
			"slime","condensate","residue","plasma",
		],
	},
	"ghost":{
		"base_name":["ghost","spirit"],
		"lesser_prefix":["lesser","weak","dim"],
		"greater_prefix":["greater","empowered","radiant"],
		"base_stats":{
			"strength":8,
			"constitution":6,
			"dexterity":8,
			"intelligence":10,
			"wisdom":11,
			"cunning":10,
		},
		"attributes":{
			"attack":15,
			"magic":15,
			"willpower":12,
			"armour":0,
			"evasion":15,
			"accuracy":10,
			"penetration":10,
			"speed":0,
			"critical":4,
		},
		"resistance":{
			"impact":0.5,
			"cutting":0.5,
			"piercing":0.5,
		},
		"variants":{
			"haunting":{
				"name_prefix":["haunting","stalking","night"],
				"abilities":["feral_darkness_magic","dirty_fighting","evasion"],
				"resistance":{
					"darkness":0.5,
				},
			},
			"light":{
				"name_prefix":["light","shining","radiant"],
				"abilities":["feral_light_magic","feral_impact_light_magic"],
				"resistance":{
					"light":0.75,
				},
			},
			"darkness":{
				"name_prefix":["dark","shadow","black"],
				"abilities":["feral_darkness_magic","feral_impact_darkness_magic"],
				"resistance":{
					"darkness":0.75,
				},
			},
		},
		"materials":[
			"slime","condensate","residue","plasma",
		],
	},
	"golem":{
		"base_name":["golem"],
		"lesser_prefix":["lesser","tiny","small"],
		"greater_prefix":["greater","great","large"],
		"base_stats":{
			"strength":10,
			"constitution":14,
			"dexterity":6,
			"intelligence":8,
			"wisdom":8,
			"cunning":4,
		},
		"attributes":{
			"attack":10,
			"magic":10,
			"willpower":15,
			"armour":15,
			"evasion":0,
			"accuracy":15,
			"penetration":0,
			"speed":-2,
			"critical":-2,
		},
		"resistance":{
			"cutting":0.25,
			"piercing":0.25,
		},
		"abilities":["armour"],
		"variants":{
			"stone":{
				"name_prefix":["stone","rock"],
				"abilities":["feral_earth_magic","feral_impact_earth_magic"],
				"resistance":{
					"cutting":0.5,
					"piercing":0.5,
					"impact":0.5,
				},
			},
			"fire":{
				"name_prefix":["fire","lava","magma","blaze"],
				"abilities":["feral_fire_magic","feral_impact_fire_magic"],
				"resistance":{
					"fire":0.75,
				},
			},
			"water":{
				"name_prefix":["water","aqua","ocean","hydro"],
				"abilities":["feral_water_magic","feral_impact_water_magic"],
				"resistance":{
					"water":0.75,
				},
			},
			"ice":{
				"name_prefix":["ice","cold","frozen","frost"],
				"abilities":["feral_ice_magic","feral_impact_ice_magic"],
				"resistance":{
					"ice":0.75,
				},
			},
			"lightning":{
				"name_prefix":["lightning","electro","thunder"],
				"abilities":["feral_lightning_magic","feral_impact_lightning_magic"],
				"resistance":{
					"lightning":0.75,
				},
			},
			"light":{
				"name_prefix":["light","shining","radiant"],
				"abilities":["feral_light_magic","feral_impact_light_magic"],
				"resistance":{
					"light":0.75,
				},
			},
			"darkness":{
				"name_prefix":["dark","shadow","black"],
				"abilities":["feral_darkness_magic","feral_impact_darkness_magic"],
				"resistance":{
					"darkness":0.75,
				},
			},
		},
		"equipment_drop_chance":0.1,
		"equipment_enchantment_chance":0.2,
		"equipment_quality":0.75,
		"materials":[
			"pebble","stone","gem","residue","resin",
		],
	},
	"paper_golem":{
		"base_name":["golem"],
		"lesser_prefix":["lesser","profane","small"],
		"greater_prefix":["greater","great","large"],
		"base_stats":{
			"strength":9,
			"constitution":13,
			"dexterity":8,
			"intelligence":11,
			"wisdom":11,
			"cunning":8,
		},
		"attributes":{
			"attack":5,
			"magic":15,
			"willpower":20,
			"armour":5,
			"evasion":5,
			"accuracy":15,
			"penetration":-2,
			"speed":-2,
			"critical":-6,
		},
		"resistance":{
			"poison":0.5,
			"impact":0.25,
			"fire":-0.5,
			"ice":0.5,
			"water":-0.5,
			"light":0.25,
			"darkness":0.25,
		},
		"abilities":["evasion","feral_impact_earth_magic"],
		"variants":{
			"wood":{
				"name_prefix":["wood"],
				"abilities":["feral_earth_magic","feral_water_magic"],
				"resistance":{
					"cutting":0.25,
					"piercing":0.25,
					"impact":0.25,
				},
			},
			"paper":{
				"name_prefix":["paper","scroll"],
				"abilities":["elemental_magic","defensive_magic"],
				"resistance":{
					"lightnint":0.25,
					"poison":0.25,
				},
			},
		},
		"equipment_drop_chance":0.1,
		"equipment_enchantment_chance":0.2,
		"equipment_quality":0.75,
		"exp":18,
		"materials":[
			"pebble","gem","residue","resin","paper","parchement",
		],
	},
	"fearfire_golem":{
		"base_name":["golem"],
		"lesser_prefix":["lesser","tiny","small"],
		"greater_prefix":["greater","great","large"],
		"base_stats":{
			"strength":11,
			"constitution":13,
			"dexterity":6,
			"intelligence":10,
			"wisdom":7,
			"cunning":4,
		},
		"attributes":{
			"attack":15,
			"magic":15,
			"willpower":20,
			"armour":20,
			"evasion":0,
			"accuracy":25,
			"penetration":0,
			"speed":-2,
			"critical":-4,
		},
		"resistance":{
			"poison":0.5,
			"impact":0.3,
			"fire":0.3,
			"darkness":0.3,
		},
		"abilities":["armour","dirty_fighting"],
		"variants":{
			"lava":{
				"name_prefix":["lava","magma","molten "],
				"abilities":["feral_fire_magic","feral_impact_fire_magic","feral_impact_earth_magic"],
				"resistance":{
					"fire":0.75,
					"earth":0.75,
					"water":-0.25,
					"ice":-0.25,
				},
			},
			"fear":{
				"name_prefix":["fear","fearfire","black "],
				"abilities":["feral_darkness_magic","feral_impact_darkness_magic","feral_impact_fire_magic"],
				"resistance":{
					"fire":0.75,
					"darkness":0.75,
					"light":-0.25,
					"earth":-0.25,
				},
			},
		},
		"equipment_drop_chance":0.1,
		"equipment_enchantment_chance":0.2,
		"equipment_quality":0.75,
		"exp":18,
		"materials":[
			"pebble","stone","gem","residue","resin","dust","oil",
		],
	},
	"nanite_golem":{
		"base_name":["golem"],
		"lesser_prefix":["lesser","tiny","small"],
		"greater_prefix":["greater","great","large"],
		"base_stats":{
			"strength":11,
			"constitution":15,
			"dexterity":6,
			"intelligence":7,
			"wisdom":7,
			"cunning":4,
		},
		"attributes":{
			"attack":15,
			"magic":15,
			"willpower":10,
			"armour":20,
			"evasion":5,
			"accuracy":30,
			"penetration":0,
			"speed":-2,
			"critical":-4,
		},
		"resistance":{
			"poison":0.5,
			"impact":0.3,
			"light":0.3,
			"darkness":0.3,
			"water":-0.2,
			"lightning":-0.2,
		},
		"abilities":["armour","high_tech_impact"],
		"variants":{
			"nanite":{
				"name_prefix":["nanite","high-tech"],
				"abilities":["feral_impact_lightning_magic","high_tech_cutting","shield"],
				"resistance":{
					"cutting":0.5,
					"piercing":0.5,
					"impact":0.5,
					"lightning":-0.5,
				},
			},
			"electrified":{
				"name_prefix":["eletronic","high-tech"],
				"abilities":["feral_impact_lightning_magic","high_tech_ranged","defensive_magic"],
				"resistance":{
					"earth":0.3,
					"wind":0.3,
					"lightning":0.2,
					"water":-0.5,
				},
			},
		},
		"equipment_drop_chance":0.1,
		"equipment_enchantment_chance":0.2,
		"equipment_quality":0.75,
		"exp":18,
		"materials":[
			"stone","gem","oil","battery","processing_unit","scrap","wires","ram_module",
		],
	},
	"zombie":{
		"base_name":["zombie"],
		"lesser_prefix":["weak","hobbling","rotten","decomposing","half"],
		"greater_prefix":["fresh","strong","super"],
		"base_stats":{
			"strength":7,
			"constitution":5,
			"dexterity":4,
			"intelligence":4,
			"wisdom":4,
			"cunning":2,
		},
		"attributes":{
			"attack":10,
			"magic":10,
			"willpower":-2,
			"armour":2,
			"evasion":0,
			"accuracy":5,
			"penetration":5,
			"speed":0,
			"critical":-2,
		},
		"resistance":{
			"poison":0.5,
			"light":-0.5,
			"darkness":0.25,
		},
		"abilities":["claws"],
		"equipment_drop_chance":0.1,
		"equipment_enchantment_chance":0.1,
		"equipment_quality":0.75,
		"materials":[
			"bone","skin","nail","insistine","meat","hair","parchement",
		],
	},
	"ghoul":{
		"base_name":["ghoul"],
		"lesser_prefix":["weak","rotten","decomposing","hungry"],
		"greater_prefix":["fresh","strong","well fed"],
		"base_stats":{
			"strength":9,
			"constitution":6,
			"dexterity":6,
			"intelligence":6,
			"wisdom":5,
			"cunning":4,
		},
		"attributes":{
			"attack":15,
			"magic":10,
			"willpower":4,
			"armour":4,
			"evasion":15,
			"accuracy":20,
			"penetration":10,
			"speed":-1,
			"critical":0,
		},
		"resistance":{
			"poison":0.5,
			"light":-0.5,
			"darkness":0.25,
		},
		"abilities":["claws","toxic_bite","feral_impact_darkness_magic"],
		"exp":15,
		"equipment_drop_chance":0.1,
		"equipment_enchantment_chance":0.1,
		"equipment_quality":1.0,
		"materials":[
			"skin","nail","insistine","meat","hair","parchement",
		],
	},
	"skeleton":{
		"base_name":["skeleton"],
		"lesser_prefix":["weak","dusty","crippled"],
		"greater_prefix":["polished","strong","reinforced"],
		"base_stats":{
			"strength":7,
			"constitution":7,
			"dexterity":6,
			"intelligence":4,
			"wisdom":4,
			"cunning":4,
		},
		"attributes":{
			"attack":15,
			"magic":10,
			"willpower":0,
			"armour":5,
			"evasion":10,
			"accuracy":15,
			"penetration":0,
			"speed":0,
			"critical":2,
		},
		"resistance":{
			"poison":0.5,
			"light":-0.5,
			"darkness":0.25,
			"piercing":0.25,
			"cutting":0.25,
			"impact":-0.25,
		},
		"variants":{
			"default":{
				"abilities":["light_weapons"]
			},
			"fighter":{
				"name_suffix":["fighter","battler"],
				"abilities":["light_weapons","heavy_weapons"],
			},
			"tank":{
				"name_prefix":["heavy","armoured","armour-clad"],
				"abilities":["heavy_weapons","shield","armour"],
				"attributes":{
					"armour":15,
					"speed":-1,
					"critical":0,
				},
			},
			"archer":{
				"name_suffix":["archer","shooter"],
				"abilities":["archery","evasion"],
			},
			"mage":{
				"name_suffix":["mage","caster"],
				"abilities":["elemental_magic","feral_fire_magic","feral_darkness_magic"],
			},
		},
		"exp":15,
		"equipment_drop_chance":0.1,
		"equipment_enchantment_chance":0.1,
		"equipment_quality":1.0,
		"materials":[
			"skull","ore","cloth","paper","parchement","dust",
		],
	},
	"mummy":{
		"base_name":["mummy"],
		"lesser_prefix":["weak","dusty","crippled"],
		"greater_prefix":["intact","strong","reinforced"],
		"base_stats":{
			"strength":7,
			"constitution":7,
			"dexterity":8,
			"intelligence":9,
			"wisdom":9,
			"cunning":8,
		},
		"attributes":{
			"attack":15,
			"magic":15,
			"willpower":5,
			"armour":4,
			"evasion":5,
			"accuracy":10,
			"penetration":5,
			"speed":0,
			"critical":4,
		},
		"resistance":{
			"poison":0.5,
			"acid":0.5,
			"light":-0.25,
			"darkness":0.25,
			"fire":-0.5,
			"water":-0.25,
			"ice":0.25,
		},
		"abilities":["claws"],
		"variants":{
			"default":{
				"abilities":["dirty_fighting"]
			},
			"fighter":{
				"name_suffix":["fighter","battler"],
				"abilities":["light_weapons","toxic_bite"],
			},
			"tank":{
				"name_prefix":["heavy","armoured","armour-clad"],
				"abilities":["heavy_weapons","shield","armour"],
				"attributes":{
					"armour":15,
					"speed":-1,
					"critical":2,
				},
			},
			"priest":{
				"name_suffix":["priest","healer"],
				"abilities":["healing","defensive_magic"],
			},
			"mage":{
				"name_suffix":["mage","caster"],
				"abilities":["elemental_magic","feral_fire_magic","feral_darkness_magic"],
			},
		},
		"exp":15,
		"equipment_drop_chance":0.1,
		"equipment_enchantment_chance":0.2,
		"equipment_quality":1.0,
		"materials":[
			"heart","ore","cloth","paper","parchement","wrapping","dust",
		],
	},
	"vampire":{
		"base_name":["vampire"],
		"lesser_prefix":["weak","young","drained"],
		"greater_prefix":["elite","strong","ancient"],
		"base_stats":{
			"strength":8,
			"constitution":9,
			"dexterity":12,
			"intelligence":12,
			"wisdom":10,
			"cunning":12,
		},
		"attributes":{
			"attack":15,
			"magic":15,
			"willpower":15,
			"armour":10,
			"evasion":15,
			"accuracy":15,
			"penetration":10,
			"speed":0,
			"critical":6,
		},
		"resistance":{
			"piercing":0.25,
			"cutting":0.25,
			"fire":-0.25,
			"ice":0.25,
			"poison":0.5,
			"darkness":0.5,
			"light":-0.5,
		},
		"abilities":["draining_bite","celestial_magic"],
		"variants":{
			"default":{
				"abilities":["light_weapons","dirty_fighting"],
			},
			"fighter":{
				"name_suffix":["fighter","combatant"],
				"abilities":["light_weapons","infuse_elemental"],
			},
			"lord":{
				"name_suffix":["lord","nobleman"],
				"abilities":["heavy_weapons","shield","armour"],
				"attributes":{
					"willpower":20,
					"armour":20,
					"speed":-1,
				},
			},
			"mage":{
				"name_suffix":["mage","caster"],
				"abilities":["elemental_magic","feral_darkness_magic"],
			},
		},
		"exp":15,
		"equipment_drop_chance":0.1,
		"equipment_enchantment_chance":0.2,
		"equipment_quality":1.0,
		"materials":[
			"heart","ore","cloth","paper","parchement","wrapping","dust",
		],
	},
	"undead":{
		"base_name":["necromancer","thrall master","undead fiend"],
		"lesser_prefix":["weakened","unexpirienced","drained"],
		"greater_prefix":["elite","powerful","ancient"],
		"base_stats":{
			"strength":7,
			"constitution":9,
			"dexterity":10,
			"intelligence":12,
			"wisdom":12,
			"cunning":12,
		},
		"attributes":{
			"attack":8,
			"magic":15,
			"willpower":10,
			"armour":5,
			"evasion":12,
			"accuracy":16,
			"penetration":10,
			"speed":0,
			"critical":8,
		},
		"resistance":{
			"acid":-0.25,
			"poison":0.5,
			"darkness":0.5,
			"light":-0.5,
		},
		"abilities":["draining_bite","celestial_magic","defensive_magic"],
		"exp":20,
		"equipment_drop_chance":0.25,
		"equipment_enchantment_chance":0.2,
		"equipment_quality":1.0,
		"materials":[
			"heart","ore","cloth","paper","parchement","dust","hair",
		],
	},
	"lich":{
		"base_name":["lich"],
		"lesser_prefix":["minor","lesser","weakened"],
		"greater_prefix":["ancient","greater","powerful"],
		"base_stats":{
			"strength":6,
			"constitution":12,
			"dexterity":9,
			"intelligence":13,
			"wisdom":12,
			"cunning":12,
		},
		"attributes":{
			"attack":10,
			"magic":18,
			"willpower":16,
			"armour":4,
			"evasion":10,
			"accuracy":16,
			"penetration":8,
			"speed":0,
			"critical":8,
		},
		"resistance":{
			"acid":-0.25,
			"poison":0.5,
			"darkness":0.5,
			"light":-0.5,
			"ice":0.25,
		},
		"abilities":["draining_bite","celestial_magic","elemental_magic","defensive_magic","feral_cutting_darkness_magic"],
		"exp":25,
		"equipment_drop_chance":0.25,
		"equipment_enchantment_chance":0.2,
		"equipment_quality":1.0,
		"materials":[
			"ore","cloth","paper","parchement","dust","hair","bone","skin",
		],
	},
	"goblin":{
		"base_name":["goblin"],
		"lesser_prefix":["weak","small","miniature","tiny","hobbling","one-eyed"],
		"greater_prefix":["strong","large","oversized"],
		"base_stats":{
			"strength":4,
			"constitution":5,
			"dexterity":6,
			"intelligence":4,
			"wisdom":6,
			"cunning":4,
		},
		"attributes":{
			"attack":10,
			"magic":10,
			"willpower":-2,
			"armour":2,
			"evasion":5,
			"accuracy":10,
			"penetration":0,
			"speed":0,
			"critical":-2,
		},
		"resistance":{
			"poison":0.25,
		},
		"variants":{
			"fighter":{
				"name_suffix":["fighter","battler"],
				"abilities":["light_weapons"],
			},
			"poisoner":{
				"name_suffix":["poisoner"],
				"abilities":["light_weapons","poisonous_dagger"],
			},
			"slinger":{
				"name_suffix":["slinger","shooter"],
				"abilities":["archery"],
				"attributes":{
					"penetration":5,
				}
			},
			"archer":{
				"name_suffix":["archer","shooter"],
				"abilities":["archery"],
				"attributes":{
					"accuracy":20,
				}
			},
			"shaman":{
				"name_suffix":["shaman"],
				"abilities":["nature_magic","healing"],
			},
		},
		"equipment_drop_chance":0.1,
		"equipment_enchantment_chance":0.1,
		"equipment_quality":0.75,
		"materials":[
			"bone","skin","nail","tongue","ear","hair","eye_ball","wood","ore","paper"
		],
	},
	"hobgoblin":{
		"base_name":["hobgoblin"],
		"lesser_prefix":["weak","small","one-eyed","old"],
		"greater_prefix":["strong","huge","oversized","elite"],
		"base_stats":{
			"strength":8,
			"constitution":10,
			"dexterity":8,
			"intelligence":5,
			"wisdom":5,
			"cunning":6,
		},
		"attributes":{
			"attack":10,
			"magic":5,
			"willpower":10,
			"armour":12,
			"evasion":10,
			"accuracy":15,
			"penetration":5,
			"speed":0,
			"critical":4,
		},
		"resistance":{
			"poison":0.25,
		},
		"variants":{
			"basher":{
				"name_suffix":["basher","smasher"],
				"abilities":["heavy_weapons","shield","brawling"],
			},
			"brawler":{
				"name_suffix":["brawler","brute"],
				"abilities":["light_weapons","brawling","armour"],
			},
		},
		"exp":20,
		"equipment_drop_chance":0.2,
		"equipment_enchantment_chance":0.2,
		"equipment_quality":1.0,
		"materials":[
			"bone","skin","nail","tongue","ear","hair","eye_ball","wood","ore","paper"
		],
	},
	"gnoll":{
		"base_name":["gnoll"],
		"lesser_prefix":["weak","small","old","hobbling","one-eyed"],
		"greater_prefix":["strong","large","elite"],
		"base_stats":{
			"strength":7,
			"constitution":8,
			"dexterity":8,
			"intelligence":7,
			"wisdom":8,
			"cunning":6,
		},
		"attributes":{
			"attack":10,
			"magic":10,
			"willpower":0,
			"armour":6,
			"evasion":15,
			"accuracy":20,
			"penetration":10,
			"speed":0,
			"critical":2,
		},
		"resistance":{
			"poison":0.25,
		},
		"variants":{
			"fighter":{
				"name_suffix":["fighter","battler"],
				"abilities":["light_weapons","heavy_weapons"],
			},
			"spearman":{
				"name_suffix":["spearman","lancer"],
				"abilities":["light_weapons","evasion"],
			},
			"archer":{
				"name_suffix":["archer","shooter"],
				"abilities":["archery"],
				"attributes":{
					"accuracy":30,
				}
			},
			"mage":{
				"name_suffix":["mage"],
				"abilities":["elemental_magic","elemental_magic"],
			},
			"shaman":{
				"name_suffix":["shaman"],
				"abilities":["nature_magic","healing"],
			},
		},
		"exp":15,
		"equipment_drop_chance":0.2,
		"equipment_enchantment_chance":0.1,
		"equipment_quality":0.75,
		"materials":[
			"bone","skin","nail","tongue","ear","hair","eye_ball","wood","ore","paper"
		],
	},
	"troll":{
		"base_name":["troll"],
		"lesser_prefix":["weakened","old","young","scarred"],
		"greater_prefix":["strong","towering","elite","huge"],
		"base_stats":{
			"strength":15,
			"constitution":30,
			"dexterity":6,
			"intelligence":10,
			"wisdom":10,
			"cunning":4,
		},
		"attributes":{
			"attack":20,
			"magic":20,
			"willpower":5,
			"armour":15,
			"evasion":-5,
			"accuracy":15,
			"penetration":0,
			"speed":-5,
			"critical":-4,
		},
		"resistance":{
			"poison":0.25,
			"ice":0.25,
			"water":0.25,
		},
		"variants":{
			"brute":{
				"name_suffix":["brute","brawler"],
				"abilities":["brawling","heavy_weapons"],
				"attributes":{
					"penetration":5,
				},
			},
			"warrior":{
				"name_suffix":["warrior","battler"],
				"abilities":["heavy_weapons","shield","armour"],
			},
			"welp":{
				"name_suffix":["welp"],
				"abilities":["brawling"],
				"base_stats":{
					"strength":12,
					"constitution":22,
					"dexterity":9,
					"cunning":5,
					"critical":0,
				},
				"attributes":{
					"attack":10,
					"armour":5,
					"evasion":10,
					"accuracy":20,
					"speed":-2,
				},
			},
			"mage":{
				"name_suffix":["mage"],
				"abilities":["elemental_magic","nature_magic"],
				"attributes":{
					"accuracy":20,
				},
			},
		},
		"exp":30,
		"equipment_drop_chance":0.25,
		"equipment_enchantment_chance":0.1,
		"equipment_quality":1.25,
		"materials":[
			"skin","hide","insistine","nail","eye_ball","wood","ore","paper","testicle",
		],
	},
	"wolf":{
		"base_name":["wolf","hound","dog"],
		"lesser_prefix":["hungry","starved","injured"],
		"greater_prefix":["feral","huge","aggressive","ferocious"],
		"abilities":["fangs","claws"],
		"base_stats":{
			"strength":8,
			"constitution":8,
			"dexterity":10,
			"intelligence":4,
			"wisdom":4,
			"cunning":6,
		},
		"attributes":{
			"attack":10,
			"magic":5,
			"willpower":0,
			"armour":4,
			"evasion":5,
			"accuracy":10,
			"penetration":0,
			"speed":0,
			"critical":2,
		},
		"materials":[
			"fur","tail","fang","bone","eye_ball","meat"
		],
	},
	"strong_wolf":{
		"base_name":["wolf","hound","beast"],
		"lesser_prefix":["hungry","starved","injured"],
		"greater_prefix":["feral","huge","aggressive","ferocious"],
		"abilities":["fangs","claws"],
		"base_stats":{
			"strength":9,
			"constitution":10,
			"dexterity":12,
			"intelligence":6,
			"wisdom":6,
			"cunning":8,
		},
		"attributes":{
			"attack":10,
			"magic":5,
			"willpower":-2,
			"armour":5,
			"evasion":10,
			"accuracy":15,
			"penetration":5,
			"speed":0,
			"critical":4,
		},
		"resistance":{
			"impact":0.25,
		},
		"variants":{
			"bleeding":{
				"name_suffix":["razor","sable-tooth"],
				"abilities":["lacerating_fangs"],
				"attributes":{
					"penetration":10,
				},
			},
			"nimble":{
				"name_prefix":["nimble","agile"],
				"abilities":["evasion"],
				"attributes":{
					"evasion":15,
				},
			},
		},
		"exp":15,
		"materials":[
			"fur","tail","fang","bone","eye_ball","meat"
		],
	},
	"elemental_wolf":{
		"base_name":["wolf","hound","beast"],
		"lesser_prefix":["hungry","starved","injured"],
		"greater_prefix":["feral","huge","aggressive","ferocious"],
		"abilities":["fangs","claws"],
		"base_stats":{
			"strength":8,
			"constitution":9,
			"dexterity":12,
			"intelligence":8,
			"wisdom":7,
			"cunning":8,
		},
		"attributes":{
			"attack":5,
			"magic":5,
			"willpower":8,
			"armour":4,
			"evasion":10,
			"accuracy":15,
			"penetration":5,
			"speed":0,
			"critical":4,
		},
		"resistance":{
			"light":0.25,
			"darkness":0.25,
		},
		"variants":{
			"fire":{
				"name_prefix":["fire","blaze","flare"],
				"abilities":["feral_fire_magic","feral_cutting_fire_magic"],
				"resistance":{
					"fire":0.75,
				},
			},
			"water":{
				"name_prefix":["water","aqua","ocean"],
				"abilities":["feral_water_magic","feral_cutting_water_magic"],
				"resistance":{
					"water":0.75,
				},
			},
			"ice":{
				"name_prefix":["ice","cold","frozen","frost"],
				"abilities":["feral_ice_magic","feral_cutting_ice_magic"],
				"resistance":{
					"ice":0.75,
				},
			},
			"lightning":{
				"name_prefix":["lightning","electro","thunder"],
				"abilities":["feral_lightning_magic","feral_cutting_lightning_magic"],
				"resistance":{
					"lightning":0.75,
				},
			},
		},
		"exp":15,
		"materials":[
			"fur","tail","fang","bone","meat","residue",
		],
	},
	"tiger":{
		"base_name":["tiger","lion","panther"],
		"lesser_prefix":["small","starved","injured"],
		"greater_prefix":["feral","huge","aggressive","ferocious"],
		"abilities":["fangs","claws"],
		"base_stats":{
			"strength":9,
			"constitution":10,
			"dexterity":14,
			"intelligence":8,
			"wisdom":8,
			"cunning":10,
		},
		"attributes":{
			"attack":10,
			"magic":5,
			"willpower":2,
			"armour":5,
			"evasion":10,
			"accuracy":20,
			"penetration":10,
			"speed":0,
			"critical":8,
		},
		"variants":{
			"bleeding":{
				"name_suffix":["razor","sable-tooth"],
				"abilities":["lacerating_fangs"],
				"attributes":{
					"penetration":15,
				},
			},
			"nimble":{
				"name_prefix":["nimble","agile"],
				"abilities":["evasion"],
				"attributes":{
					"evasion":20,
				},
			},
			"sneaky":{
				"name_prefix":["sneaky","sly"],
				"abilities":["dirty_fighting"],
				"attributes":{
					"accuracy":25,
				},
			},
		},
		"exp":18,
		"materials":[
			"fur","tail","fang","eye_ball","meat","ear"
		],
	},
	"boar":{
		"base_name":["boar"],
		"lesser_prefix":["hungry","starved","injured"],
		"greater_prefix":["feral","huge","aggressive","ferocious"],
		"abilities":["fangs","claws"],
		"base_stats":{
			"strength":8,
			"constitution":12,
			"dexterity":6,
			"intelligence":4,
			"wisdom":4,
			"cunning":6,
		},
		"attributes":{
			"attack":10,
			"magic":5,
			"willpower":8,
			"armour":8,
			"evasion":5,
			"accuracy":5,
			"penetration":0,
			"speed":-1,
			"critical":-2,
		},
		"materials":[
			"fur","leather","bone","meat",
		],
	},
	"snap_turtle":{
		"base_name":["snap turtle"],
		"lesser_prefix":["young","starved","injured"],
		"greater_prefix":["feral","huge","sturdy","ferocious"],
		"abilities":["fangs","feral_impact_water_magic","armour"],
		"base_stats":{
			"strength":8,
			"constitution":12,
			"dexterity":6,
			"intelligence":6,
			"wisdom":6,
			"cunning":8,
		},
		"attributes":{
			"attack":10,
			"magic":5,
			"willpower":0,
			"armour":15,
			"evasion":-2,
			"accuracy":8,
			"penetration":0,
			"speed":-2,
			"critical":0,
		},
		"materials":[
			"shell","leather","bone","meat",
		],
	},
	"yeti":{
		"base_name":["yeti"],
		"lesser_prefix":["hungry","starved","injured"],
		"greater_prefix":["feral","huge","aggressive","ferocious"],
		"abilities":["claws","brawling","dirty_fighting"],
		"base_stats":{
			"strength":12,
			"constitution":16,
			"dexterity":9,
			"intelligence":6,
			"wisdom":6,
			"cunning":8,
		},
		"attributes":{
			"attack":15,
			"magic":10,
			"willpower":6,
			"armour":12,
			"evasion":10,
			"accuracy":10,
			"penetration":5,
			"speed":0,
			"critical":2,
		},
		"variants":{
			"default":{},
			"shielder":{
				"name_suffix":["shield-bearer","protector"],
				"abilities":["shield","armour"],
				"attributes":{
					"attack":5,
					"magic":5,
					"willpower":15,
					"armour":20,
					"penetration":0,
				},
			},
			"shaman":{
				"name_suffix":["shaman"],
				"abilities":["healing","defensive_magic"],
				"base_stats":{
					"strength":10,
					"wisdom":11,
					"cunning":9,
				},
			},
		},
		"materials":[
			"fur","hair","bone","eye_ball","meat","ear","cloth","plank","testicle","kidney",
		],
		"exp":15,
		"equipment_drop_chance":0.2,
		"equipment_enchantment_chance":0.1,
		"equipment_quality":1.0,
	},
	"minotaur":{
		"base_name":["minotaur"],
		"lesser_prefix":["hungry","young","inexperienced"],
		"greater_prefix":["huge","towering","ferocious"],
		"abilities":["heavy_weapons","brawling","dirty_fighting"],
		"base_stats":{
			"strength":14,
			"constitution":16,
			"dexterity":8,
			"intelligence":7,
			"wisdom":7,
			"cunning":10,
		},
		"attributes":{
			"attack":15,
			"magic":5,
			"willpower":10,
			"armour":15,
			"evasion":8,
			"accuracy":12,
			"penetration":4,
			"speed":0,
			"critical":4,
		},
		"variants":{
			"default":{},
			"shielder":{
				"name_suffix":["shield-bearer","protector"],
				"abilities":["shield","armour"],
				"attributes":{
					"attack":10,
					"magic":0,
					"willpower":15,
					"armour":20,
					"penetration":0,
					"critical":0,
				},
			},
			"skirmisher":{
				"name_suffix":["skirmisher","lancer"],
				"abilities":["light_weapons","evasion"],
				"attributes":{
					"magic":-5,
					"willpower":5,
					"armour":5,
					"evasion":15,
					"accuracy":16,
					"penetration":10,
					"critical":6,
				},
			},
			"shaman":{
				"name_suffix":["shaman"],
				"abilities":["healing","feral_fire_magic","feral_ice_magic"],
				"base_stats":{
					"strength":10,
					"constitution":12,
					"intelligence":11,
					"wisdom":11,
				},
			},
		},
		"materials":[
			"fur","hair","bone","eye_ball","meat","ear","cloth","plank","testicle","insistine",
		],
		"exp":21,
		"equipment_drop_chance":0.2,
		"equipment_enchantment_chance":0.1,
		"equipment_quality":1.0,
	},
	"crab":{
		"base_name":["crab"],
		"lesser_prefix":["small","weak","injured"],
		"greater_prefix":["king","tank","hard","oversized"],
		"abilities":["claws","armour","feral_impact_water_magic"],
		"base_stats":{
			"strength":8,
			"constitution":12,
			"dexterity":4,
			"intelligence":8,
			"wisdom":8,
			"cunning":6,
		},
		"attributes":{
			"attack":10,
			"magic":10,
			"willpower":12,
			"armour":15,
			"evasion":0,
			"accuracy":5,
			"penetration":0,
			"speed":-2,
			"critical":0,
		},
		"resistance":{
			"water":0.5,
		},
		"variants":{
			"default":{
				"abilities":["defensive_magic"],
			},
			"magical":{
				"name_prefix":["magical","glowing"],
				"abilities":["feral_water_magic","feral_earth_magic"],
				"attributes":{
					"attack":5,
					"magic":15,
					"armour":5,
				},
			},
			"sturdy":{
				"name_prefix":["sturdy","battle-prooved"],
				"abilities":["brawling","feral_impact_earth_magic"],
				"base_stats":{
					"constitution":14,
					"cunning":5,
				},
				"attributes":{
					"attack":15,
					"magic":5,
					"armour":20,
				},
			},
		},
		"materials":[
			"meat","pincer","shell","pebble",
		],
	},
	"scorpion":{
		"base_name":["scorpion"],
		"lesser_prefix":["small","weak","injured"],
		"greater_prefix":["king","deadly","hard","oversized"],
		"abilities":["claws","armour","feral_cutting_poison_magic"],
		"base_stats":{
			"strength":9,
			"constitution":12,
			"dexterity":8,
			"intelligence":10,
			"wisdom":10,
			"cunning":8,
		},
		"attributes":{
			"attack":15,
			"magic":10,
			"willpower":5,
			"armour":9,
			"evasion":5,
			"accuracy":10,
			"penetration":0,
			"speed":-1,
			"critical":4,
		},
		"resistance":{
			"fire":0.25,
			"light":0.25,
		},
		"variants":{
			"default":{
				"abilities":["evasion"],
			},
			"magical":{
				"name_prefix":["magical","arcane"],
				"abilities":["feral_poison_magic","feral_fire_magic"],
				"attributes":{
					"attack":10,
					"magic":15,
					"armour":4,
				},
			},
			"sturdy":{
				"name_prefix":["sturdy","battle-prooved"],
				"abilities":["brawling","feral_impact_fire_magic"],
				"base_stats":{
					"constitution":14,
					"cunning":7,
				},
				"attributes":{
					"attack":15,
					"magic":5,
					"armour":16,
				},
			},
		},
		"materials":[
			"bone","meat","pincer","shell",
		],
	},
	"snake":{
		"base_name":["snake"],
		"lesser_prefix":["small","weak","starving"],
		"greater_prefix":["king","deadly","poisonous"],
		"abilities":["fangs","toxic_bite","evasion"],
		"base_stats":{
			"strength":5,
			"constitution":7,
			"dexterity":12,
			"intelligence":7,
			"wisdom":8,
			"cunning":9,
		},
		"attributes":{
			"attack":10,
			"magic":10,
			"willpower":-2,
			"armour":2,
			"evasion":8,
			"accuracy":20,
			"penetration":5,
			"speed":1,
			"critical":4,
		},
		"resistance":{
			"poison":0.25,
			"acid":0.25,
		},
		"variants":{
			"default":{},
			"huge":{
				"name_prefix":["giant","fat"],
				"abilities":["brawling"],
				"base_stats":{
					"strength":10,
					"constitution":8,
					"dexterity":10,
					"cunning":8,
				},
				"attributes":{
					"attack":15,
					"magic":0,
					"evasion":5,
					"accuracy":10,
					"speed":0,
				},
			},
			"magical":{
				"name_prefix":["magical","arcane"],
				"abilities":["feral_poison_magic"],
				"attributes":{
					"attack":5,
					"magic":15,
					"willpower":8,
					"armour":0,
				},
			},
			"agile":{
				"name_prefix":["agile","fast"],
				"base_stats":{
					"constitution":6,
					"dexterity":13,
				},
				"attributes":{
					"attack":5,
					"magic":5,
					"evasion":15,
					"speed":2,
				},
			},
		},
		"materials":[
			"leather","meat","fang","venom","scale",
		],
	},
	"water_snake":{
		"base_name":["water snake","sea snake"],
		"lesser_prefix":["small","weak","shallow"],
		"greater_prefix":["king","deadly","deep"],
		"abilities":["toxic_bite","feral_water_magic","feral_cutting_water_magic","evasion"],
		"base_stats":{
			"strength":5,
			"constitution":7,
			"dexterity":12,
			"intelligence":9,
			"wisdom":10,
			"cunning":10,
		},
		"attributes":{
			"attack":10,
			"magic":15,
			"willpower":4,
			"armour":2,
			"evasion":8,
			"accuracy":20,
			"penetration":10,
			"speed":2,
			"critical":6,
		},
		"resistance":{
			"poison":0.25,
			"acid":0.25,
			"water":0.5,
			"ice":-0.25,
		},
		"exp":15,
		"materials":[
			"leather","meat","fang","venom","scale",
		],
	},
	"sky_snake":{
		"base_name":["sky snake","air snake"],
		"lesser_prefix":["small","weak","dim"],
		"greater_prefix":["king","deadly","astral"],
		"abilities":["toxic_bite","feral_wind_magic","feral_cutting_wind_magic","evasion"],
		"base_stats":{
			"strength":5,
			"constitution":7,
			"dexterity":12,
			"intelligence":10,
			"wisdom":9,
			"cunning":10,
		},
		"attributes":{
			"attack":10,
			"magic":16,
			"willpower":4,
			"armour":2,
			"evasion":10,
			"accuracy":18,
			"penetration":12,
			"speed":2,
			"critical":7,
		},
		"resistance":{
			"poison":0.25,
			"acid":0.25,
			"wind":0.5,
			"earth":-0.25,
		},
		"exp":17,
		"materials":[
			"leather","meat","fang","venom","scale",
		],
	},
	"bat":{
		"base_name":["bat"],
		"lesser_prefix":["tiny","small","confused"],
		"greater_prefix":["feral","huge","strong"],
		"abilities":["fangs","evasion"],
		"base_stats":{
			"strength":4,
			"constitution":4,
			"dexterity":12,
			"intelligence":8,
			"wisdom":8,
			"cunning":6,
		},
		"attributes":{
			"attack":5,
			"magic":5,
			"willpower":-4,
			"armour":1,
			"evasion":10,
			"accuracy":18,
			"penetration":5,
			"speed":5,
			"critical":0,
		},
		"resistance":{
			"wind":-0.5,
		},
		"variants":{
			"default":{},
			"vampiric":{
				"name_prefix":["vampiric","blood-sucking"],
				"resistance":{
					"darkness":0.25,
				},
				"abilities":["draining_bite"],
			},
			"fast":{
				"name_prefix":["fast","agile"],
				"attributes":{
					"armour":0,
					"speed":8,
				},
			},
		},
		"materials":[
			"fang","wing","claw"
		],
	},
	"spider":{
		"base_name":["spider"],
		"lesser_prefix":["tiny","small","slow"],
		"greater_prefix":["feral","huge","fanged"],
		"abilities":["fangs","toxic_bite","evasion"],
		"base_stats":{
			"strength":4,
			"constitution":4,
			"dexterity":10,
			"intelligence":10,
			"wisdom":8,
			"cunning":6,
		},
		"attributes":{
			"attack":10,
			"magic":10,
			"willpower":-4,
			"armour":2,
			"evasion":15,
			"accuracy":15,
			"penetration":5,
			"speed":0,
			"critical":0,
		},
		"resistance":{
			"fire":-0.5,
			"ice":0.25,
			"poison":0.25,
		},
		"variants":{
			"default":{},
			"spell_weaver":{
				"name_prefix":["spell-weaver","magical","arcane"],
				"abilities":["defensive_magic","feral_ice_magic","feral_acid_magic"],
				"attributes":{
					"magic":15,
					"willpower":15,
				},
			},
			"net_weaver":{
				"name_prefix":["web-casting","silk-spitter","spitting"],
				"abilities":["web"],
				"attributes":{
					"accuracy":25,
					"penetration":10,
				},
			},
		},
		"materials":[
			"fang","silk","venom","hair"
		],
	},
	"harpy":{
		"base_name":["harpy"],
		"lesser_prefix":["small","weak"],
		"greater_prefix":["feral","clawed","strong"],
		"abilities":["claws","feral_wind_magic","evasion"],
		"base_stats":{
			"strength":8,
			"constitution":8,
			"dexterity":12,
			"intelligence":10,
			"wisdom":9,
			"cunning":6,
		},
		"attributes":{
			"attack":10,
			"magic":10,
			"willpower":4,
			"armour":8,
			"evasion":15,
			"accuracy":20,
			"penetration":5,
			"speed":0,
			"critical":2,
		},
		"resistance":{
			"wind":-0.5,
		},
		"variants":{
			"default":{
				"abilities":["dirty_fighting"],
			},
			"fast":{
				"name_prefix":["fast","agile"],
				"attributes":{
					"willpower":10,
					"armour":4,
					"evasion":20,
					"accuracy":25,
				},
			},
			"heavy":{
				"name_prefix":["heavy","armoured"],
				"abilities":["defensive_magic"],
				"attributes":{
					"willpower":10,
					"armour":18,
					"evasion":5,
					"accuracy":10,
					"critical":0,
				},
			},
			"shaman":{
				"name_suffix":["shaman","priestess"],
				"abilities":["nature_magic","defensive_magic"],
				"attributes":{
					"magic":20,
					"willpower":25,
					"armour":3,
					"evasion":15,
				},
			},
		},
		"materials":[
			"fang","wing","claw","heart","hair","feather",
		],
	},
	"drake":{
		"base_name":["drake"],
		"lesser_prefix":["hungry","starved","baby"],
		"greater_prefix":["feral","aggressive","ferocious"],
		"abilities":["fangs","claws"],
		"base_stats":{
			"strength":8,
			"constitution":9,
			"dexterity":12,
			"intelligence":11,
			"wisdom":10,
			"cunning":8,
		},
		"attributes":{
			"attack":5,
			"magic":10,
			"willpower":10,
			"armour":15,
			"evasion":10,
			"accuracy":10,
			"penetration":0,
			"speed":0,
			"critical":2,
		},
		"resistance":{
			"fire":0.25,
			"water":0.25,
			"ice":0.25,
			"lightning":0.25,
		},
		"variants":{
			"fire":{
				"name_prefix":["fire","blaze","flare"],
				"abilities":["feral_fire_magic","feral_cutting_fire_magic"],
			},
			"water":{
				"name_prefix":["water","aqua","ocean","hydro"],
				"abilities":["feral_water_magic","feral_cutting_water_magic"],
			},
			"ice":{
				"name_prefix":["ice","cold","frozen","frost"],
				"abilities":["feral_ice_magic","feral_cutting_ice_magic"],
			},
			"lightning":{
				"name_prefix":["lightning","electro","thunder"],
				"abilities":["feral_lightning_magic","feral_cutting_lightning_magic"],
			},
		},
		"exp":15,
		"materials":[
			"scale","scale","fang","bone","wing","gem",
		],
	},
	"imp":{
		"base_name":["imp"],
		"lesser_prefix":["weak","small","crippled","injured"],
		"greater_prefix":["strong","dangerous","elite"],
		"base_stats":{
			"strength":7,
			"constitution":7,
			"dexterity":9,
			"intelligence":9,
			"wisdom":8,
			"cunning":6,
		},
		"attributes":{
			"attack":10,
			"magic":10,
			"willpower":6,
			"armour":3,
			"evasion":15,
			"accuracy":10,
			"penetration":5,
			"speed":0,
			"critical":-1,
		},
		"resistance":{
			"darkness":0.25,
			"light":-0.25,
		},
		"abilities":["celestial_magic","elemental_magic"],
		"variants":{
			"default":{},
			"slasher":{
				"name_suffix":["slasher","battler"],
				"abilities":["claws"],
			},
			"poisoner":{
				"name_suffix":["poisoner"],
				"abilities":["poisonous_dagger"],
			},
			"shaman":{
				"name_suffix":["shaman"],
				"abilities":["nature_magic","healing"],
			},
		},
		"exp":15,
		"equipment_drop_chance":0.2,
		"equipment_enchantment_chance":0.1,
		"equipment_quality":0.75,
		"materials":[
			"skin","leather","nail","paper","tail","heart",
		],
	},
	"demon":{
		"base_name":["demon"],
		"lesser_prefix":["weak","feral","crippled"],
		"greater_prefix":["strong","super","elite"],
		"base_stats":{
			"strength":10,
			"constitution":12,
			"dexterity":12,
			"intelligence":12,
			"wisdom":10,
			"cunning":12,
		},
		"attributes":{
			"attack":15,
			"magic":15,
			"willpower":7,
			"armour":10,
			"evasion":10,
			"accuracy":20,
			"penetration":5,
			"speed":0,
			"critical":3,
		},
		"resistance":{
			"darkness":0.5,
			"light":-0.5,
		},
		"abilities":["celestial_magic","elemental_magic"],
		"variants":{
			"default":{},
			"bulwark":{
				"name_suffix":["bulwark","fighter"],
				"abilities":["infuse_elemental","heavy_weapons","armour"],
				"attributes":{
					"armour":20,
				},
			},
			"warrior":{
				"name_suffix":["warrior","soldier"],
				"abilities":["infuse_elemental","light_weapons","shield","feral_cutting_darkness_magic"],
				"attributes":{
					"critical":6,
				},
			},
			"fire":{
				"name_suffix":["warcaster","archmage","conjurer"],
				"abilities":["feral_darkness_magic","feral_cutting_fire_magic"],
				"attributes":{
					"willpower":11,
				},
			},
		},
		"exp":30,
		"equipment_drop_chance":0.25,
		"equipment_enchantment_chance":0.2,
		"equipment_quality":1.25,
		"materials":[
			"skin","leather","nail","paper","tail","heart","kidney","horn","ingot",
		],
	},
	"plant":{
		"base_name":["plant","tree"],
		"lesser_prefix":["barely moving","gnarly","singed"],
		"greater_prefix":["feral","ferocious","flesh-eating","blood-covered"],
		"abilities":["brawling","defensive_magic"],
		"resistance":{
			"fire":-0.5,
			"ice":0.5,
			"piercing":0.5,
		},
		"base_stats":{
			"strength":8,
			"constitution":12,
			"dexterity":6,
			"intelligence":8,
			"wisdom":12,
			"cunning":4,
		},
		"attributes":{
			"attack":10,
			"magic":10,
			"willpower":0,
			"armour":6,
			"evasion":0,
			"accuracy":5,
			"penetration":0,
			"speed":-2,
			"critical":-1,
		},
		"variants":{
			"animated":{
				"name_prefix":["animated","living"],
				"abilities":["feral_impact_earth_magic","armour"],
				"attributes":{
					"attack":15,
					"willpower":10,
				},
			},
			"enchanted":{
				"name_prefix":["enchanted","magical"],
				"abilities":["feral_impact_ice_magic","feral_impact_lightning_magic"],
				"attributes":{
					"magic":15,
					"willpower":5,
					"armour":2,
				},
			},
			"poisonous":{
				"name_prefix":["poisonous","toxic"],
				"abilities":["feral_impact_poison_magic","feral_poison_magic","feral_acid_magic"],
				"attributes":{
					"magic":15,
					"speed":-5,
				},
			},
		},
		"materials":[
			"wood","wood","leaf","cotton","root","cabbage"
		],
	},
	"thug":{
		"base_name":["thug","thief","rogue","robber"],
		"lesser_prefix":["weak","one-eyed","pathetic","unexperienced"],
		"greater_prefix":["strong","elite","brutal","lethal","master"],
		"base_stats":{
			"strength":10,
			"constitution":10,
			"dexterity":12,
			"intelligence":6,
			"wisdom":8,
			"cunning":10,
		},
		"attributes":{
			"attack":10,
			"magic":0,
			"willpower":0,
			"armour":10,
			"evasion":15,
			"accuracy":20,
			"penetration":10,
			"speed":2,
			"critical":3,
		},
		"abilities":["light_weapons","dirty_fighting","evasion"],
		"variants":{
			"backstabber":{
				"name_suffix":["backstabber"],
				"attributes":{
					"willpower":4,
					"armour":2,
					"penetration":20,
					"speed":4,
				},
			},
			"brawler":{
				"name_suffix":["brawler","battler"],
				"abilities":["brawling"],
				"attributes":{
					"armour":15,
				},
			},
			"poisoner":{
				"name_suffix":["poisoner"],
				"abilities":["poisonous_dagger"],
				"attributes":{
					"speed":4,
				},
			},
			"slinger":{
				"name_suffix":["slinger","shooter"],
				"abilities":["archery"],
				"attributes":{
					"accuracy":25,
				},
			},
		},
		"exp":20,
		"equipment_drop_chance":0.3,
		"equipment_enchantment_chance":0.1,
		"equipment_quality":1.0,
	},
	"guard":{
		"base_name":["guard","vanguard","fighter","body guard"],
		"lesser_prefix":["weak","one-eyed","pathetic","unexperienced"],
		"greater_prefix":["strong","elite","master","fierce"],
		"base_stats":{
			"strength":12,
			"constitution":12,
			"dexterity":10,
			"intelligence":6,
			"wisdom":8,
			"cunning":6,
		},
		"attributes":{
			"attack":25,
			"magic":0,
			"willpower":4,
			"armour":18,
			"evasion":10,
			"accuracy":15,
			"penetration":0,
			"speed":-2,
			"critical":1,
		},
		"abilities":["heavy_weapons","armour"],
		"variants":{
			"shield":{
				"name_suffix":["shield-bearer"],
				"abilities":["shield"],
				"attributes":{
					"willpower":6,
					"armour":25,
					"speed":-4,
				},
			},
			"heavy":{
				"name_prefix":["heavy","armoured"],
				"abilities":["shield"],
				"base_stats":{
					"constitution":14,
				},
				"attributes":{
					"willpower":10,
					"armour":26,
					"evasion":5,
					"accuracy":15,
					"speed":-8,
				},
			},
			"brawler":{
				"name_suffix":["brawler","battler"],
				"abilities":["brawling"],
				"attributes":{
					"willpower":12,
					"accuracy":20,
				},
			},
			"archer":{
				"name_suffix":["archer","shooter"],
				"abilities":["archery"],
				"attributes":{
					"accuracy":25,
				}
			},
		},
		"exp":20,
		"equipment_drop_chance":0.3,
		"equipment_enchantment_chance":0.1,
		"equipment_quality":1.0,
	},
	"fighter":{
		"base_name":["fighter","battler","brawler"],
		"lesser_prefix":["weak","pathetic","unexperienced"],
		"greater_prefix":["strong","elite","expirienced","fierce"],
		"base_stats":{
			"strength":11,
			"constitution":11,
			"dexterity":10,
			"intelligence":6,
			"wisdom":6,
			"cunning":7,
		},
		"attributes":{
			"attack":15,
			"magic":5,
			"willpower":4,
			"armour":10,
			"evasion":10,
			"accuracy":15,
			"penetration":0,
			"speed":0,
			"critical":2,
		},
		"abilities":["brawling","dirty_fighting"],
		"variants":{
			"default":{},
			"shield":{
				"name_suffix":["shield-bearer"],
				"abilities":["shield"],
				"attributes":{
					"willpower":12,
					"armour":15,
					"speed":-2,
				},
			},
			"heavy":{
				"name_prefix":["heavy","armoured"],
				"abilities":["heavy_weapons"],
				"attributes":{
					"willpower":4,
					"armour":20,
					"evasion":5,
					"accuracy":10,
					"speed":-2,
				},
			},
			"light":{
				"name_prefix":["agile","fast"],
				"abilities":["evasion"],
				"attributes":{
					"willpower":0,
					"armour":4,
					"evasion":20,
					"accuracy":20,
				},
			},
		},
		"exp":15,
		"equipment_drop_chance":0.2,
		"equipment_enchantment_chance":0.1,
		"equipment_quality":1.0,
	},
	"human":{
		"base_name":["swordsman","human"],
		"lesser_prefix":["weak","pathetic","unexperienced"],
		"greater_prefix":["strong","elite","fierce"],
		"base_stats":{
			"strength":12,
			"constitution":12,
			"dexterity":10,
			"intelligence":6,
			"wisdom":8,
			"cunning":8,
		},
		"attributes":{
			"attack":20,
			"magic":0,
			"willpower":4,
			"armour":18,
			"evasion":10,
			"accuracy":15,
			"penetration":0,
			"speed":-1,
			"critical":1,
		},
		"abilities":["light_weapons","heavy_weapons","evasion","armour"],
		"exp":20,
		"equipment_drop_chance":0.3,
		"equipment_enchantment_chance":0.1,
		"equipment_quality":1.0,
	},
	"halfling":{
		"base_name":["halfling"],
		"lesser_prefix":["weak","tiny","small"],
		"greater_prefix":["strong","elite","fierce"],
		"base_stats":{
			"strength":9,
			"constitution":9,
			"dexterity":12,
			"intelligence":6,
			"wisdom":6,
			"cunning":10,
		},
		"attributes":{
			"attack":15,
			"magic":0,
			"willpower":6,
			"armour":15,
			"evasion":15,
			"accuracy":20,
			"penetration":5,
			"speed":0,
			"critical":5,
		},
		"abilities":["light_weapons","dirty_fighting","evasion"],
		"exp":20,
		"equipment_drop_chance":0.3,
		"equipment_enchantment_chance":0.1,
		"equipment_quality":1.0,
	},
	"elf":{
		"base_name":["elf"],
		"lesser_prefix":["weak","young","pacifist"],
		"greater_prefix":["strong","elite","fierce"],
		"base_stats":{
			"strength":8,
			"constitution":8,
			"dexterity":11,
			"intelligence":9,
			"wisdom":9,
			"cunning":6,
		},
		"attributes":{
			"attack":15,
			"magic":15,
			"willpower":10,
			"armour":10,
			"evasion":15,
			"accuracy":15,
			"penetration":0,
			"speed":0,
			"critical":4,
		},
		"abilities":["light_weapons","archery","nature_magic","healing","evasion"],
		"exp":20,
		"equipment_drop_chance":0.3,
		"equipment_enchantment_chance":0.1,
		"equipment_quality":1.0,
	},
	"dwarf":{
		"base_name":["dwarf","hammerdwarf","dwarven fighter"],
		"lesser_prefix":["weak","tiny","small"],
		"greater_prefix":["sturdy","elite","fierce"],
		"base_stats":{
			"strength":13,
			"constitution":13,
			"dexterity":8,
			"intelligence":6,
			"wisdom":6,
			"cunning":6,
		},
		"attributes":{
			"attack":20,
			"magic":0,
			"willpower":10,
			"armour":20,
			"evasion":10,
			"accuracy":10,
			"penetration":0,
			"speed":0,
			"critical":10,
		},
		"abilities":["heavy_weapons","brawling","shield","armour"],
		"exp":20,
		"equipment_drop_chance":0.3,
		"equipment_enchantment_chance":0.1,
		"equipment_quality":1.0,
	},
	"naga":{
		"base_name":["naga"],
		"lesser_prefix":["weak","slow","inexperienced"],
		"greater_prefix":["strong","elite","fierce"],
		"base_stats":{
			"strength":11,
			"constitution":9,
			"dexterity":12,
			"intelligence":6,
			"wisdom":8,
			"cunning":8,
		},
		"attributes":{
			"attack":15,
			"magic":15,
			"willpower":10,
			"armour":15,
			"evasion":20,
			"accuracy":15,
			"penetration":10,
			"speed":0,
			"critical":8,
		},
		"abilities":["light_weapons","evasion"],
		"variants":{
			"fighter":{
				"name_suffix":["fighter"],
				"abilities":["heavy_weapons"],
				"attributes":{
					"attack":20,
					"armour":20,
				},
			},
			"skirmisher":{
				"name_suffix":["skirmisher"],
				"abilities":["dirty_fighting","brawling"],
				"attributes":{
					"attack":10,
					"magic":0,
					"willpower":5,
					"armour":5,
					"penetration":20,
					"speed":1,
					"critical":10,
				},
			},
			"shaman":{
				"name_suffix":["shaman"],
				"abilities":["nature_magic","healing_magic"],
				"attributes":{
					"attack":10,
					"magic":20,
					"willpower":20,
					"armour":10,
					"penetration":5,
					"critical":2,
				},
			},
			"spell_weaver":{
				"name_suffix":["spell weaver"],
				"abilities":["elemental_magic","nature_magic","defensive_magic"],
				"attributes":{
					"attack":10,
					"magic":25,
					"armour":5,
					"penetration":5,
					"critical":2,
				},
			},
		},
		"exp":20,
		"equipment_drop_chance":0.3,
		"equipment_enchantment_chance":0.1,
		"equipment_quality":1.0,
	},
	"orc":{
		"base_name":["orc"],
		"lesser_prefix":["weak","one-eyed","pathetic","injured"],
		"greater_prefix":["strong","elite","brutal"],
		"base_stats":{
			"strength":12,
			"constitution":11,
			"dexterity":11,
			"intelligence":6,
			"wisdom":8,
			"cunning":8,
		},
		"attributes":{
			"attack":20,
			"magic":5,
			"willpower":6,
			"armour":10,
			"evasion":10,
			"accuracy":15,
			"penetration":0,
			"speed":0,
			"critical":1,
		},
		"abilities":["heavy_weapons"],
		"variants":{
			"backstabber":{
				"name_suffix":["backstabber"],
				"abilities":["light_weapons","dirty_fighting","evasion"],
				"attributes":{
					"willpower":8,
					"armour":2,
					"penetration":20,
					"speed":1,
				},
			},
			"brawler":{
				"name_suffix":["brawler","battler"],
				"abilities":["brawling","armour"],
				"attributes":{
					"armour":15,
				},
			},
			"bulwark":{
				"name_suffix":["bulwark","fighter"],
				"abilities":["heavy_weapons","armour"],
				"attributes":{
					"armour":22,
				},
			},
			"poisoner":{
				"name_suffix":["poisoner"],
				"abilities":["light_weapons","dirty_fighting","poisonous_dagger"],
				"attributes":{
					"speed":1,
				},
			},
			"archer":{
				"name_suffix":["archer","shooter"],
				"abilities":["archery","evasion"],
				"attributes":{
					"accuracy":25,
				}
			},
			"warcaster":{
				"name_suffix":["war caster","mage"],
				"abilities":["elemental_magic","nature_magic"],
				"attributes":{
					"magic":20,
				}
			},
			"priest":{
				"name_suffix":["priest","shaman"],
				"abilities":["healing","defensive_magic"],
				"attributes":{
					"magic":10,
					"willpower":20,
				}
			},
		},
		"exp":20,
		"equipment_drop_chance":0.3,
		"equipment_enchantment_chance":0.1,
		"equipment_quality":1.0,
	},
	"ogre":{
		"base_name":["ogre"],
		"lesser_prefix":["weak","young","injured"],
		"greater_prefix":["strong","fierce","brutal"],
		"base_stats":{
			"strength":12,
			"constitution":14,
			"dexterity":8,
			"intelligence":7,
			"wisdom":7,
			"cunning":8,
		},
		"attributes":{
			"attack":20,
			"magic":10,
			"willpower":10,
			"armour":15,
			"evasion":0,
			"accuracy":10,
			"penetration":0,
			"speed":0,
			"critical":0,
		},
		"abilities":["heavy_weapons","brawling"],
		"variants":{
			"fighter":{
				"name_suffix":["fighter","warrior"],
				"abilities":["light_weapons","armour"],
			},
			"brawler":{
				"name_suffix":["brawler","battler"],
				"abilities":["armour"],
				"attributes":{
					"armour":15,
				},
			},
			"archer":{
				"name_suffix":["archer","shooter"],
				"abilities":["archery","evasion"],
				"attributes":{
					"accuracy":20,
				}
			},
			"mage":{
				"name_suffix":["mage","spell caster"],
				"abilities":["elemental_magic","nature_magic"],
				"attributes":{
					"magic":20,
				}
			},
		},
		"exp":20,
		"equipment_drop_chance":0.3,
		"equipment_enchantment_chance":0.1,
		"equipment_quality":1.0,
	},
	"wale":{
		"base_name":["wale"],
		"lesser_prefix":["weak","young","baby"],
		"greater_prefix":["heavy","fierce","huge"],
		"base_stats":{
			"strength":12,
			"constitution":16,
			"dexterity":6,
			"intelligence":8,
			"wisdom":8,
			"cunning":8,
		},
		"attributes":{
			"attack":10,
			"magic":16,
			"willpower":14,
			"armour":18,
			"evasion":0,
			"accuracy":8,
			"penetration":0,
			"speed":0,
			"critical":2,
		},
		"abilities":["shield","feral_water_magic","feral_impact_water_magic"],
		"variants":{
			"basher":{
				"name_suffix":["basher","smasher"],
				"abilities":["brawling","armour"],
			},
			"impaler":{
				"name_suffix":["impaler","unicorn"],
				"abilities":["light_weapons","horn"],
			},
			"shaman":{
				"name_suffix":["shaman","matriarch"],
				"abilities":["brawling","healing"],
			},
		},
		"exp":20,
		"equipment_drop_chance":0.2,
		"equipment_enchantment_chance":0.1,
		"equipment_quality":1.0,
		"materials":[
			"leather","leather","meat","meat","bone","oil",
		],
	},
	"drone":{
		"base_name":["drone"],
		"lesser_prefix":["damaged","barely flying","outdated","rusty","steam-powered"],
		"greater_prefix":["elite","reinforced","super","mega","giga","ultra"],
		"abilities":["gun_slinging","high_tech_ranged","high_tech_cutting"],
		"base_stats":{
			"strength":8,
			"constitution":9,
			"dexterity":12,
			"intelligence":11,
			"wisdom":10,
			"cunning":4,
		},
		"attributes":{
			"attack":5,
			"magic":10,
			"willpower":0,
			"armour":6,
			"evasion":14,
			"accuracy":10,
			"penetration":0,
			"speed":0,
			"critical":1,
		},
		"resistance":{
			"poison":0.5,
			"acid":-0.5,
		},
		"variants":{
			"fire":{
				"name_prefix":["fire","blaze","flare"],
				"abilities":["feral_fire_magic"],
			},
			"water":{
				"name_prefix":["water","aqua","hydro"],
				"abilities":["feral_water_magic"],
			},
			"ice":{
				"name_prefix":["ice","freezing","frost"],
				"abilities":["feral_ice_magic"],
			},
			"lightning":{
				"name_prefix":["lightning","electro","thunder"],
				"abilities":["feral_lightning_magic"],
			},
		},
		"exp":15,
		"materials":[
			"cog","scrap","ingot","paper","cloth","tissue","shell","battery","processing_unit","wires",
		],
	},
	"robot":{
		"base_name":["robot","android"],
		"lesser_prefix":["rusty","damaged","small","malfunctioning","steam-powered"],
		"greater_prefix":["elite","super","mega","giga","ultra"],
		"base_stats":{
			"strength":11,
			"constitution":12,
			"dexterity":9,
			"intelligence":10,
			"wisdom":10,
			"cunning":6,
		},
		"attributes":{
			"attack":20,
			"magic":10,
			"willpower":8,
			"armour":20,
			"evasion":15,
			"accuracy":15,
			"penetration":0,
			"speed":0,
			"critical":1,
		},
		"resistance":{
			"poison":0.5,
			"acid":-0.5,
		},
		"abilities":["high_tech_cutting","high_tech_ranged","armour"],
		"variants":{
			"shield":{
				"name_suffix":["shield-bearer"],
				"abilities":["shield","defensive_magic"],
				"attributes":{
					"willpower":16,
					"armour":25,
					"speed":-1,
				},
			},
			"heavy":{
				"name_prefix":["heavy","armoured"],
				"abilities":["shield","brawling"],
				"base_stats":{
					"constitution":15,
					"cunning":5,
				},
				"attributes":{
					"willpower":4,
					"armour":25,
					"evasion":0,
					"accuracy":10,
					"speed":-2,
				},
			},
			"artillery":{
				"name_prefix":["artillery","bombarding"],
				"abilities":["elemental_magic","nature_magic"],
			},
		},
		"exp":20,
		"equipment_drop_chance":0.1,
		"equipment_enchantment_chance":0.2,
		"equipment_quality":1.0,
		"materials":[
			"cog","scrap","paper","synth_skin","cloth","tissue","shell","battery",
			"processing_unit","heart","ram_module",
		],
	},
	"cyborg":{
		"base_name":["cyborg"],
		"lesser_prefix":["rusty","malfunctioning","steam-powered"],
		"greater_prefix":["elite","super","mega","ultra"],
		"base_stats":{
			"strength":10,
			"constitution":11,
			"dexterity":10,
			"intelligence":11,
			"wisdom":11,
			"cunning":8,
		},
		"attributes":{
			"attack":18,
			"magic":12,
			"willpower":10,
			"armour":15,
			"evasion":15,
			"accuracy":15,
			"penetration":0,
			"speed":0,
			"critical":4,
		},
		"resistance":{
			"poison":0.25,
			"acid":-0.25,
		},
		"abilities":["light_weapons","high_tech_cutting","gun_slinging","armour"],
		"exp":25,
		"equipment_drop_chance":0.1,
		"equipment_enchantment_chance":0.2,
		"equipment_quality":1.0,
		"materials":[
			"cog","scrap","paper","skin","synth_skin","cloth","tissue","shell",
			"processing_unit","heart","ram_module",
		],
	},
	"mech":{
		"base_name":["mech"],
		"lesser_prefix":["damaged","rusty","malfunctioning","steam-powered"],
		"greater_prefix":["towering","elite","huge","gigantic"],
		"base_stats":{
			"strength":15,
			"constitution":30,
			"dexterity":6,
			"intelligence":10,
			"wisdom":10,
			"cunning":6,
		},
		"attributes":{
			"attack":20,
			"magic":20,
			"willpower":20,
			"armour":25,
			"evasion":0,
			"accuracy":20,
			"penetration":0,
			"speed":-5,
			"critical":-1,
		},
		"resistance":{
			"poison":0.5,
			"acid":-0.5,
		},
		"abilities":["high_tech_impact","high_tech_ranged","armour"],
		"variants":{
			"default":{},
			"inferno":{
				"name_prefix":["inferno","hellfire"],
				"abilities":["feral_fire_magic","high_tech_cutting"],
			},
			"brawler":{
				"name_suffix":["brawler","battler"],
				"abilities":["brawling"],
			},
			"artillery":{
				"name_suffix":["artillery","bombardment"],
				"abilities":["elemental_magic","nature_magic"],
			},
		},
		"exp":30,
		"equipment_drop_chance":0.2,
		"equipment_enchantment_chance":0.2,
		"equipment_quality":1.25,
		"materials":[
			"cog","scrap","paper","synth_skin","cloth","tissue","shell","battery",
			"processing_unit","heart","wires",
		],
	},
}


func create_tooltip(creature: Characters.Character) -> String:
	var text: String = creature.name + "\n" + tr("LEVEL") + " " + str(creature.level) + " " + tr("TIER"+str(clamp(creature.tier + 2, 0, 5))) + " " + creature.base_name + "\n\n" + tr("STATS") + ":\n"
	for k in creature.stats.keys():
		text += "  " + tr(k.to_upper()) + ": " + str(creature.stats[k]) + "\n"
	text += "\n"
	for k in creature.attributes.keys():
		text += "  " + tr(k.to_upper()) + ": " + str(creature.attributes[k]) + "\n"
	text += "\n"
	if creature.damage.size()>0:
		text += tr("DAMAGE") + ":\n"
		for k in creature.damage.keys():
			text += "  " + tr(k.to_upper()) + ": " + str(int(100*creature.damage[k])) + "%\n"
		text += "\n"
	if creature.resistance.size()>0:
		text += tr("RESISTANCE") + ":\n"
		for k in creature.resistance.keys():
			text += "  " + tr(k.to_upper()) + ": " + str(int(100*creature.resistance[k])) + "%\n"
		text += "\n"
	text += tr("SKILLS") + ":\n"
	for skill in creature.skills:
		text += "  " + skill.name + "\n"
	return text


func create_enemy(type: String, level: int, tier:= 0) -> Characters.Enemy:
	if !BASE_ENEMIES.has(type):
		type = BASE_ENEMIES.keys().pick_random()
	var dict: Dictionary = BASE_ENEMIES[type]
	var enemy:= {
		"name":dict.base_name.pick_random(),
		"level":level,
		"tier":tier,
		"experience":10,
		"stats":dict.base_stats.duplicate(),
		"abilities":[],
		"resistance":{},
		"damage":{},
		"skills":[],
		"status":[],
		"delay":randf_range(0.0,1.0),
		"position":-1,
	}
	var tier_multiplier:= 1.0
	var level_multiplier: float = 1.0 + min(0.1 + 0.001*level, 0.2)*(level-1)
	var num_skills: int = max(1 + 2*tier, -1)
	var max_range:= 0
	var ret: Characters.Enemy
	enemy.base_name = enemy.name
	enemy.name_prefix = enemy.name
	if dict.has("experience"):
		enemy.experience = dict.exp
	if dict.has("abilities"):
		enemy.abilities += dict.abilities
		num_skills += dict.abilities.size()/2
	if dict.has("attributes"):
		enemy.attributes_add = dict.attributes.duplicate()
	if dict.has("resistance"):
		enemy.resistance = dict.resistance.duplicate()
	if dict.has("variants"):
		var variant: Dictionary = dict.variants.values().pick_random()
		if variant.has("base_name"):
			enemy.name = variant.base_name.pick_random()
			enemy.name_prefix = enemy.name
		if variant.has("name_prefix"):
			var prefix: String = variant.name_prefix.pick_random()
			enemy.name = prefix+" "+enemy.name
			enemy.name_prefix = prefix
		if variant.has("name_suffix"):
			enemy.name = enemy.name+" "+variant.name_suffix.pick_random()
		if variant.has("abilities"):
			enemy.abilities += variant.abilities
		if variant.has("base_stats"):
			for k in variant.base_stats.keys():
				enemy.stats[k] = variant.base_stats[k]
		if variant.has("resistance"):
			for k in variant.resistance.keys():
				enemy.resistance[k] = variant.resistance[k]
	if tier<0:
		enemy.name = dict.lesser_prefix.pick_random()+" "+enemy.name
		tier_multiplier = 1.0/pow(1.5, -tier)
	elif tier>0:
		enemy.name = dict.greater_prefix.pick_random()+" "+enemy.name
		tier_multiplier = pow(1.5, tier)
	enemy.name = enemy.name.capitalize()
	enemy.experience *= tier_multiplier*level_multiplier*(0.3 + 0.025*enemy.level)
	for k in enemy.stats.keys():
		enemy.stats[k] = int(enemy.stats[k]*(0.5 + 0.5*tier_multiplier*level_multiplier))
	for k in enemy.attributes_add.keys():
		enemy.attributes_add[k] = int(enemy.attributes_add[k]*(0.5 + 0.5*tier_multiplier*level_multiplier))
	enemy.attributes_add.attack += int(enemy.level)
	enemy.attributes_add.magic += int(enemy.level)
	enemy.attributes_add.willpower += int(1.5*enemy.level)
	enemy.attributes_add.armour += int(1.5*enemy.level)
	if enemy.abilities.size()>0:
		num_skills = max(num_skills, 1)
		for i in range(num_skills):
			var skill:= Skills.create_random_skill(enemy.abilities)
			skill.level = int(max(level/6 + 4*tier, 1))
			if has_node("/root/Main"):
				get_node("/root/Main").upgrade_skill(skill)
			enemy.skills.push_back(skill)
	if dict.has("materials"):
		enemy.materials = dict.materials
	if dict.has("equipment_drop_chance"):
		enemy.equipment_drop_chance = dict.equipment_drop_chance
	if dict.has("equipment_quality"):
		enemy.equipment_quality = dict.equipment_quality
	if dict.has("equipment_enchantment_chance"):
		enemy.equipment_enchantment_chance = dict.equipment_enchantment_chance
	for skill in enemy.skills:
		if skill.range>max_range:
			max_range = skill.range
	enemy.position = -max_range
	ret = Characters.Enemy.new(enemy)
	ret.recover()
	ret.description = create_tooltip(ret)
	return ret
